version: v1
deploy:
  is: False # False # False for dev purpose
  dev: 'http://127.0.0.1:8000'
  prod: 'https://p7-data-science-openclassrooms.herokuapp.com'

resources:
  zip: "resources.zip"
  unzip: ""
