version: v1
clients_database_preprocessed: "../dataset/cleaned/data_test_preprocessed_vf.csv"
classifier: "../models/LGBM/LGBMClassifier_fold_0.joblib"

clients_database: "../dataset/source/application_test.csv"
preprocessing:
  application: "../models/preprocessing/OneHotEncoder_application.joblib"
  bureau: "../models/preprocessing/OneHotEncoder_bureau.joblib"
  bureau_balance: "../models/preprocessing/OneHotEncoder_bureau_balance.joblib"
  credit_card_balance: "../models/preprocessing/OneHotEncoder_credit_card_balance.joblib"
  POS_CASH_balance: "../models/preprocessing/OneHotEncoder_POS_CASH_balance.joblib"
  previous_application: "../models/preprocessing/OneHotEncoder_previous_application.joblib"

# dashboard : selectionner un num de client et ds infos sur lui, feature importance etc
# score obtenu : proba / accepté ou pas
# cas réel : ici sûr pas d'ajout de client / dans dashboard : variable avec curseur
# evaluation sur le dashboard si tout apparait bien et sur modelisation : Grid, SMOTE, fonction cout métier
# api pas trop

