version: v1
resources:
  zip: "resources.zip"
  unzip: ""
clients_database_preprocessed: "resources/data_test_preprocessed_vf.csv"
classifier: "resources/LGBMClassifier_fold_0.joblib"

# For v2
clients_database: "dataset/source/application_test.csv"
preprocessing:
  application: "model_preparation/models/preprocessing/OneHotEncoder_application.joblib"
  bureau: "model_preparation/models/preprocessing/OneHotEncoder_bureau.joblib"
  bureau_balance: "model_preparation/models/preprocessing/OneHotEncoder_bureau_balance.joblib"
  credit_card_balance: "model_preparation/models/preprocessing/OneHotEncoder_credit_card_balance.joblib"
  POS_CASH_balance: "model_preparation/models/preprocessing/OneHotEncoder_POS_CASH_balance.joblib"
  previous_application: "model_preparation/models/preprocessing/OneHotEncoder_previous_application.joblib"

# dashboard : selectionner un num de client et ds infos sur lui, feature importance etc
# score obtenu : proba / accepté ou pas
# cas réel : ici sûr pas d'ajout de client / dans dashboard : variable avec curseur
# evaluation sur le dashboard si tout apparait bien et sur modelisation : Grid, SMOTE, fonction cout métier
# api pas trop


